# Generated by Django 5.2.1 on 2025-07-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sections',
            field=models.ManyToManyField(related_name='posts', to='school.section'),
        ),
    ]
