# Generated by Django 5.2.1 on 2025-07-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_placement_placement_result'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.card')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(choices=[('islam', 'Islam'), ('christianity', 'Christianity'), ('other', 'Other')], max_length=20)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.card')),
                ('parent1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent1', to='users.parent')),
                ('parent2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent2', to='users.parent')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
