# Generated by Django 5.2.1 on 2025-07-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_address_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='national_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
