# Generated by Django 5.2.1 on 2025-07-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employee_address_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='register_date',
            field=models.DateField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
    ]
