# Generated by Django 5.2.1 on 2025-06-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='users.role'),
        ),
    ]
