# Generated by Django 5.2.1 on 2025-06-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employee_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='roles',
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
    ]
