# Generated by Django 5.2.1 on 2025-06-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_employee_roles_employee_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='roles',
            new_name='role',
        ),
    ]
