# Generated by Django 5.2.1 on 2025-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_grade_name'),
        ('users', '0008_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='school.subject'),
        ),
    ]
