# Generated by Django 5.2.1 on 2025-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cooperator', 'Cooperator'), ('teacher', 'Teacher'), ('receptionist', 'Receptionist')], max_length=20),
        ),
    ]
