# Generated by Django 5.2.1 on 2025-06-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_employee_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
