# Generated by Django 5.2.1 on 2025-08-01 22:42

import landingpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=landingpage.models.upload_to)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
