# Generated by Django 5.2.1 on 2025-08-01 23:20

import landingpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=landingpage.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=landingpage.models.upload_to)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('videos', models.ManyToManyField(related_name='activities', to='landingpage.video')),
            ],
        ),
    ]
