# Generated by Django 5.2.1 on 2025-08-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_video_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, related_name='activities', to='landingpage.video'),
        ),
    ]
