# Generated by Django 5.2.1 on 2025-08-01 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_activity_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('visit_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='landingpage.visitdate')),
            ],
        ),
    ]
