# Generated by Django 5.2.1 on 2025-08-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_visitdate_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
