# Generated by Django 5.2.1 on 2025-08-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_alter_visitdate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='videos',
            field=models.ManyToManyField(related_name='activities', to='landingpage.video'),
        ),
    ]
