# Generated by Django 5.2.1 on 2025-07-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='parent1_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent1_placements', to='users.card'),
        ),
        migrations.AddField(
            model_name='placement',
            name='parent2_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent2_placements', to='users.card'),
        ),
        migrations.AddField(
            model_name='placement',
            name='student_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_placements', to='users.card'),
        ),
        migrations.AddField(
            model_name='placement',
            name='placement_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.placementdate'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='section',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.section'),
        ),
        migrations.AddField(
            model_name='grade',
            name='study_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studystage'),
        ),
        migrations.AddField(
            model_name='grade',
            name='study_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studyyear'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('name', 'grade'), name='unique_section_name_per_grade'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('name', 'study_year'), name='unique_grade_name_per_study_year'),
        ),
    ]
