# Generated by Django 5.2.1 on 2025-07-13 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='school.post'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='section',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.section'),
        ),
        migrations.AddField(
            model_name='post',
            name='sections',
            field=models.ManyToManyField(related_name='posts', to='school.section'),
        ),
        migrations.AddField(
            model_name='grade',
            name='study_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studystage'),
        ),
        migrations.AddField(
            model_name='grade',
            name='study_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studyyear'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('name', 'grade'), name='unique_section_name_per_grade'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('name', 'study_year'), name='unique_grade_name_per_study_year'),
        ),
    ]
