# Generated by Django 5.2.1 on 2025-07-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], max_length=10),
        ),
    ]
