# Generated by Django 5.2.1 on 2025-08-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='student',
            new_name='students',
        ),
    ]
