# Generated by Django 5.2.1 on 2025-06-18 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_studyyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyyear',
            name='name',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Format must be YYYY/YYYY (e.g., 2020/2021)', regex='^\\d{4}/\\d{4}$')]),
        ),
    ]
