# Generated by Django 5.2.1 on 2025-07-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_attachment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
