# Generated by Django 5.2.1 on 2025-08-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='limit',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
