# Generated by Django 5.2.1 on 2025-07-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_placementdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdate',
            name='limit',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
