# Generated by Django 5.2.1 on 2025-08-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
