# Generated by Django 5.2.1 on 2025-08-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_attendance_date'),
        ('users', '0002_alter_student_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'section', 'date')},
        ),
    ]
