# Generated by Django 5.2.1 on 2025-06-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('name', 'study_year'), name='unique_grade_name_per_study_year'),
        ),
    ]
