# Generated by Django 5.2.1 on 2025-08-18 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_attendance_unique_together'),
        ('users', '0002_alter_student_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='section',
        ),
    ]
