# Generated by Django 5.2.1 on 2025-08-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_attendance_unique_together_and_more'),
        ('users', '0002_alter_student_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_attendance_per_student'),
        ),
    ]
