# Generated by Django 5.2.1 on 2025-06-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_grade_unique_grade_name_per_study_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
