# Generated by Django 5.2.1 on 2025-07-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
