# Generated by Django 5.2.1 on 2025-08-29 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='employees',
            field=models.ManyToManyField(related_name='chat_rooms', to='users.employee'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='users.student'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouproom',
            name='employees',
            field=models.ManyToManyField(related_name='group_rooms', to='users.employee'),
        ),
        migrations.AddField(
            model_name='grouproom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to='users.employee'),
        ),
        migrations.AddField(
            model_name='grouproom',
            name='students',
            field=models.ManyToManyField(related_name='group_room', to='users.student'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='chat.grouproom'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
