# Generated by Django 5.2.1 on 2025-08-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_timestamp_message_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='created_at',
        ),
    ]
