# Generated by Django 5.2.1 on 2025-08-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_grouproom_groupmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='name',
        ),
        migrations.AddField(
            model_name='grouproom',
            name='name',
            field=models.CharField(default='ff', max_length=100),
            preserve_default=False,
        ),
    ]
