# Generated by Django 5.2.1 on 2025-08-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_grouproom_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouproom',
            old_name='student',
            new_name='students',
        ),
    ]
